# Use single default monitor (see all monitors with: hyprctl monitors)
monitor=HDMI-A-1,preferred,auto,1.6

# use natural scrolling
input {
  touchpad {
    # Use natural (inverse) scrolling
    natural_scroll = true
  }
}

device {
  name = logitech-usb-receiver-mouse
  natural_scroll = true
}

# remove existing bindings
unbind = SUPER, h
unbind = SUPER, j
unbind = SUPER, k
unbind = SUPER, l

# Move focus with mainMod + arrow keys
bind = SUPER, h, movefocus, l
bind = SUPER, l, movefocus, r
bind = SUPER, k, movefocus, u
bind = SUPER, j, movefocus, d
