#!/usr/bin/env bash
## Spacevim installation script

# Fail-safe :: Return value of a pipeline is the value of the last (rightmost) 
# command to exit with a non-zero status, or zero if all commands in the 
# pipeline exit successfully
set -o pipefail

# Fail-safe :: Treat unset variables and parameters other than the special 
# parameters ‘@’ or ‘*’ as an error when performing parameter expansion.
# An error message will be written to the standard error, and a
# non-interactive shell will exit
set -u

# Naming
readonly cr_script_sn='run_270_spacevim_installation'

# State file definition
readonly cr_state_success="$HOME/.config/chezmoi/state/$cr_script_sn"

# Validate existence of state file
if [ -e "$cr_state_success" ]; then
    # Action :: Graceful exit
    exit 0
fi

# Existence directory
if [[ ! -d "$HOME/.SpaceVim" ]]; then
    # Clone repository
    git clone https://github.com/SpaceVim/SpaceVim.git "$HOME/.SpaceVim" || {
        # Git clone failure
        printf '%s\n' "FAIL :: git :: clone :: https://github.com/SpaceVim/SpaceVim.git :: $HOME/SpaceVim :: $cr_script_sn/$LINENO"

        # Exit ungracefully
        exit 1
    }
fi

# Existence directory
if [[ ! -d "$HOME/.cache/vimfiles/repos/github.com/Shougo/dein.vim" ]]; then
    # Clone repository
    git clone https://github.com/Shougo/dein.vim.git "$HOME/.cache/vimfiles/repos/github.com/Shougo/dein.vim" || {
        # Git clone failure
        printf '%s\n' "FAIL :: git :: clone :: https://github.com/Shougo/dein.vim.git :: $HOME/.cache/vimfiles/repos/github.com/Shougo/dein.vim :: $cr_script_sn/$LINENO"

        # Exit ungracefully
        exit 1
    }
fi

# Existence symlink
if [[ ! -L "$HOME/.config/nvim" ]]; then
    # $HOME/.vim
    ln -f -s -v "$HOME/.SpaceVim" "$HOME/.config/nvim" || {
        # Symlink failure
        printf '%s\n' "FAIL :: ln :: $HOME/.SpaceVim :: $HOME/.config/nvim :: $cr_script_sn/$LINENO"

        # Exit ungracefully
        exit 1
    }
fi

# Install plugins
nvim -n -c 'set nomore' '+call dein#install()' +qall || {
    # Symlink failure
    printf '%s\n' "FAIL :: nvim :: dein#install :: $cr_script_sn/$LINENO"

    # Exit ungracefully
    exit 1
}

# Success
touch "$cr_state_success" || {
    # touch failure
    printf '%s\n' "FAIL :: touch :: $cr_state_success :: $cr_script_sn/$LINENO"

    # Exit ungracefully
    exit 1
}
