#!/usr/bin/env bash
#
# Install Antibody: shell plugin manager made from the ground up thinking 
# about performance.

# Fail-safe :: Return value of a pipeline is the value of the last (rightmost) 
# command to exit with a non-zero status, or zero if all commands in the 
# pipeline exit successfully
set -o pipefail

# Fail-safe :: Treat unset variables and parameters other than the special 
# parameters ‘@’ or ‘*’ as an error when performing parameter expansion.
# An error message will be written to the standard error, and a
# non-interactive shell will exit
set -u

# Naming
readonly cr_script_sn='run_120_install_antibody'

# State file definition
readonly cr_state_success="$HOME/.config/chezmoi/state/$cr_script_sn"

# Validate existence of state file
if [ -e "$cr_state_success" ]; then
    # Action :: Graceful exit
    exit 0
fi

if [ ! -x /usr/local/bin/antibody ]; then
  (curl -sfL git.io/antibody | sudo sh -s - -b /usr/local/bin) || {
    # Curl failed
    printf '%s\n' "FAIL :: curl ::  git.io/antibody :: /usr/local/bin :: $cr_script_sn/$LINENO"

    # Exit ungracefully
    exit 1
  }
fi

# Success
touch "$cr_state_success" || {
    # touch failure
    printf '%s\n' "FAIL :: touch :: $cr_state_success :: $cr_script_sn/$LINENO"

    # Exit ungracefully
    exit 1
}
