#!/usr/bin/env bash
#
# Install Neovim
# https://github.com/neovim/neovim

# Fail-safe :: Return value of a pipeline is the value of the last (rightmost) 
# command to exit with a non-zero status, or zero if all commands in the 
# pipeline exit successfully
set -o pipefail

# Fail-safe :: Treat unset variables and parameters other than the special 
# parameters ‘@’ or ‘*’ as an error when performing parameter expansion.
# An error message will be written to the standard error, and a
# non-interactive shell will exit
set -u

# Naming
readonly cr_script_sn='run_120_install_neovim'

# State file definition
readonly cr_state_success="$HOME/.config/chezmoi/state/$cr_script_sn"

NVIM_PATH="$HOME/code/neovim"

# Validate existence of state file
if [ -e "$cr_state_success" ]; then
    # Action :: Graceful exit
    exit 0
fi

if [ ! -d "$NVIM_PATH" ]; then
    NEOVIM_URL=https://github.com/neovim/neovim.git
    (git clone $NEOVIM_URL "$NVIM_PATH") || {
        # Git clone failed
        printf '%s\n' "FAIL :: git ::  clone :: $NEOVIM_URL :: $cr_script_sn/$LINENO"

        # Exit ungracefully
        exit 1
    }

    cd "$NVIM_PATH" || exit 1
    make CMAKE_BUILD_TYPE=RelWithDebInfo && sudo make install
fi

# Success
touch "$cr_state_success" || {
    # touch failure
    printf '%s\n' "FAIL :: touch :: $cr_state_success :: $cr_script_sn/$LINENO"

    # Exit ungracefully
    exit 1
}

# vim: ft=sh
