# ███████╗████████╗ █████╗ ██████╗ ███████╗██╗  ██╗██╗██████╗
# ██╔════╝╚══██╔══╝██╔══██╗██╔══██╗██╔════╝██║  ██║██║██╔══██╗
# ███████╗   ██║   ███████║██████╔╝███████╗███████║██║██████╔╝
# ╚════██║   ██║   ██╔══██║██╔══██╗╚════██║██╔══██║██║██╔═══╝
# ███████║   ██║   ██║  ██║██║  ██║███████║██║  ██║██║██║
# ╚══════╝   ╚═╝   ╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝╚═╝╚═╝
# The minimal, blazing-fast, and infinitely customizable prompt
# https://starship.rs

# Get editor completions based on the config schema
"$schema" = "https://starship.rs/config-schema.json"

# Catppuccin all the way
palette = "catppuccin_macchiato"

# disable new line
add_newline = false

[character]
success_symbol = "[❯](bold green)" # ❯
vimcmd_symbol = "[\ue62b](green)"  # 
error_symbol = "[❯](bold red)"     # ❯

[directory]
read_only = " 󰌾"

[git_branch]
symbol = " "

[git_state]
disabled = false
rebase = "  rebasing"
merge = "  merging"
revert = " 󰕍 reverting"
cherry_pick = "  picking"
bisect = "bisecting"
am = "am'ing"
am_or_rebase = "am/rebase"

[git_metrics]
disabled = false

[git_status]
disabled = false
stashed = "   ${count}"
ahead = " 󰞙  ${count}"
behind = " 󰞖  ${count}"
diverged = " 󰓢 ${ahead_count} ${behind_count}"
conflicted = "   ${count}"
deleted = "   ${count}"
renamed = " 󰗧 ${count}"
modified = "   ${count}"
staged = "   ${count}"
untracked = " 󰧮 ${count}"

[terraform]
symbol = "󱁢 "

[kubernetes]
symbol = "☸"
disabled = false
detect_extensions = ["yaml"]
format = "[$symbol$context( ($namespace))]($style) "

[golang]
format = "[ $version](bold cyan) "

[package]
symbol = "󰏗 "
disabled = true

[docker_context]
symbol = " "
disabled = true

[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"
