# ███████╗████████╗ █████╗ ██████╗ ███████╗██╗  ██╗██╗██████╗
# ██╔════╝╚══██╔══╝██╔══██╗██╔══██╗██╔════╝██║  ██║██║██╔══██╗
# ███████╗   ██║   ███████║██████╔╝███████╗███████║██║██████╔╝
# ╚════██║   ██║   ██╔══██║██╔══██╗╚════██║██╔══██║██║██╔═══╝
# ███████║   ██║   ██║  ██║██║  ██║███████║██║  ██║██║██║
# ╚══════╝   ╚═╝   ╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝╚═╝╚═╝
# The minimal, blazing-fast, and infinitely customizable prompt
# https://starship.rs

# Get editor completions based on the config schema
"$schema" = "https://starship.rs/config-schema.json"

# disable new line
add_newline = true

format = "[$directory$git_branch$git_status]($style)$fill$container$terraform$kubernetes$python$go$line_break$character"

palette = "rose-pine"

[palettes.rose-pine]
overlay = '#26233a'
love = '#eb6f92'
gold = '#f6c177'
rose = '#ebbcba'
pine = '#31748f'
foam = '#9ccfd8'
iris = '#c4a7e7'

[character]
error_symbol = "[✗](bold love)"
success_symbol = "[❯](bold foam)"
vimcmd_symbol = "[\ue62b](green)" # 

[directory]
truncation_length = 3
truncation_symbol = "…/"
read_only = " 󰌾"

[docker_context]
symbol = " "

[fill]
symbol = ' '

[git_branch]
symbol = " "
style = "italic iris"

[golang]
format = "[ $version](bold cyan) "

[kubernetes]
symbol = "☸"
disabled = false
detect_extensions = ["yaml"]
format = "[$symbol$context( ($namespace))]($style) "

[lua]
disabled = true

[package]
disabled = true

[terraform]
symbol = "󱁢 "
