#=============================================================================
# basic.toml --- basic configuration example for SpaceVim
# Copyright (c) 2016-2020 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "nord"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "slant"
    statusline_inactive_separator = "slant"
    buffer_index_type = 4
    windows_index_type = 3
    enable_tabline_filetype_icon = false
    enable_statusline_mode = true
    statusline_unicode_symbols = true
    # Enable vim compatible mode, avoid changing origin vim key bindings
    vimcompatible = true
    # Visualization :: Filetype :: Use icons
    enable_tabline_ft_icon = true

    # Do not use relative numbers
    relativenumber = false

    # Plugin :: File manager :: Filetree manager choise
    filemanager = "nerdtree"
    # Plugin :: File manager :: Direction
    filetree_direction = "left"

    # Will be called after custom configuration file is loaded
    bootstrap_before = "bootstrap#before"
    # Will be called after Vim Enter autocmd
    bootstrap_after = "bootstrap#after"

    # Set default indent of 2 spaces
    default_indent = 2
    expand_tab = true

    autocomplete_method = "coc"

# Autocomplete code within SpaceVim, fuzzy find the candidates from multiple completion sources, expand snippet before cursor automatically
[[layers]]
    name = "autocomplete"
    auto_completion_return_key_behavior = "complete"
    auto_completion_tab_key_behavior = "smart"

[[layers]]
  name = "core#statusline"
  enable = false

# Provides syntax checking feature
[[layers]]
    name = "checkers"

# Provides a list of colorscheme
[[layers]]
    name = "colorscheme"

# Provides a heavily customized fzf centric work-flow
[[layers]]
    name = "fzf"

# Add extensive support for git
[[layers]]
    name = "git"
    git-plugin = "fugitive"

# Vimscript language support, including code completion, syntax checking and buffer formatting
[[layers]]
    name = "lang#vim"

[[layers]]
    name = "lang#python"

[[layers]]
    name = "lang#puppet"

# Edit markdown within vim, autopreview markdown in the default browser, with this layer you can also format markdown file
[[layers]]
    name = "lang#markdown"

# Shell script development layer, provides autocompletion, syntax checking, code format for bash and zsh script
[[layers]]
    name = "lang#sh"

# Provide shell support in SpaceVim
[[layers]]
    name = "shell"
    default_height = 30
    default_position = "bottom"

# Awesome UI layer for SpaceVim, provide IDE-like UI for neovim and vim in both TUI and GUI
[[layers]]
    name = "ui"
    enable_sidebar = false

[[layers]]
  name = "lsp"
  filetypes = [
    "tf"
  ]
  [layers.override_cmd]
    tf = ["terraform-ls", "serve"]

# https://github.com/pearofducks/ansible-vim :: Syntax highlighting Ansible common filetypes
[[custom_plugins]]
    name = "pearofducks/ansible-vim"
    merged = false

# https://github.com/ryanoasis/vim-devicons :: Add file type icons to Vim plugins such as NERDTree, vim-airline, vim-startify, and many more
[[custom_plugins]]
    name = "ryanoasis/vim-devicons"
    merged = false

[[custom_plugins]]
    name = "prettier/vim-prettier"
    merged = false

[[custom_plugins]]
    name = "nvim-treesitter/nvim-treesitter"
    merged = false
