#!/usr/bin/env bash

if [ $(unane) == "Darwin" ]; then
    echo "Preparing OSX environment...."
    cp Brewfile $HOME/.Brewfile

    if [ ! -f "/opt/homebrew/bin/brew" ]; then
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
    fi

    # load Brew environment
    eval "$(/opt/homebrew/bin/brew shellenv)"

    # Preparing system
    brew bundle install --global

    # Remove stale or outdated downloads
    brew cleanup --prune 0
fi

# vi: ft=bash
