#!/usr/bin/env bash

VERSION="1.24.5"
MARCH=$(uname -m)

if [ $MARCH == "x86_64" ]; then
    MARCH="amd64"
fi

if [ $(uname) == "Linux" ]; then
    echo "Download and installing Go version $VERSION..."
    curl -sLo /var/tmp/go${VERSION}.linux-${MARCH}.tar.gz https://go.dev/dl/go${VERSION}.linux-${MARCH}.tar.gz
    sudo rm -rf /usr/local/go && sudo tar -C /usr/local -xzf /var/tmp/go${VERSION}.linux-${MARCH}.tar.gz
fi

# vi: ft=bash
