#!/usr/bin/env bash

if [ $(uname) == "Darwin" ]; then
    echo "Configuring default settings for Mac OS..."
    cat /etc/pam.d/sudo_local.template | sed 's/^#auth/auth/' | sudo tee /etc/pam.d/sudo_local
    sed '/^auth/i\
auth       optional       /opt/homebrew/lib/pam/pam_reattach.so ignore_ssh
    ' /etc/pam.d/sudo_local | sudo tee /etc/pam.d/sudo_local

    # some default settings
    # Disable automatic window animations
    defaults write -g NSAutomaticWindowAnimationsEnabled -bool false
    # Save to local disk by default (disable iCloud save)
    defaults write -g NSDocumentSaveNewDocumentsToCloud -bool false
    # Expand save panel by default
    defaults write -g NSNavPanelExpandedStateForSaveMode -bool false

    # Set default folder for screen captures
    defaults write com.apple.screencapture location "~/Pictures/Screenshots"
    # Add a nice login message
    sudo defaults write /Library/Preferences/com.apple.loginwindow LoginwindowText "I use Neovim btw ⌨️"
    # map capslock to escape
    hidutil property --set '{"UserKeyMapping":[{"HIDKeyboardModifierMappingSrc":30064771129,"HIDKeyboardModifierMappingDst":30064771113}]}'
    # autohide dock and restart Dock process
    defaults write com.apple.dock autohide -bool "true" && killall Dock
    # remove old items after 30 days
    defaults write com.apple.finder FXRemoveOldTrashItems -bool "true" && killall Finder
fi

# vi: ft=bash
