## MONITORS

# Use single default monitor (see all monitors with: hyprctl monitors)
env = GDK_SCALE,1.75

## INPUTS

# use natural scrolling
input {
  kb_options = caps:escape

  touchpad {
    # Use natural (inverse) scrolling
    natural_scroll = true
  }
}

# Turn on natural scrolling for my Logitech mouse
device {
  name = lift-mouse
  natural_scroll = true
}

decoration {
    # Use round window corners
    rounding = 8
}

## BINDINGS

# remove existing bindings
unbind = SUPER, h
unbind = SUPER, j
unbind = SUPER, k
unbind = SUPER, l

# Move focus with mainMod + vim motion
bind = SUPER, h, movefocus, l
bind = SUPER, j, movefocus, d
bind = SUPER, k, movefocus, u
bind = SUPER, l, movefocus, r

unbind = SUPER SHIFT, T
bindd = SUPER SHIFT, T, Todoist, exec, omarchy-launch-webapp "https://app.todoist.com/app/today"

# NOTE(robin): allow alt-tab within Citrix clients
bind = ALT, TAB, pass, class:^(Wfica)$

## WINDOW RULES

# NOTE(robin): to disable transparancy for all windows
windowrule = opacity 1 1, class:.*

# Launch Chromium into Workspace 2
windowrule = workspace 2, class:chromium

# vim: ft=hyprlang
