## MONITORS

# Use single default monitor (see all monitors with: hyprctl monitors)
env = GDK_SCALE,1.75
# Monitor at work
monitor=DP-9,preferred,auto,1
# Monitor at customer location
monitor=DVI-I-2,preferred,auto,1

monitor=DP-3,preferred,auto,1.6
## INPUTS

# use natural scrolling
input {
  kb_options = caps:escape

  touchpad {
    # Use natural (inverse) scrolling
    natural_scroll = true
  }
}

# Turn on natural scrolling for my Logitech mouse
device {
  name = lift-mouse
  natural_scroll = true
}

decoration {
    # Use round window corners
    rounding = 8
}

## BINDINGS
# trigger when the switch is turning on
bindl = , switch:on:Lid Switch, exec, hyprctl keyword monitor "eDP-1, disable"
# trigger when the switch is turning off
bindl = , switch:off:Lid Switch, exec, hyprctl keyword monitor "eDP-1, preferred, auto, 1.6"

unbind = SUPER SHIFT, T
bindd = SUPER SHIFT, T, Todoist, exec, omarchy-launch-webapp "https://app.todoist.com/app/today"

# NOTE(robin): allow alt-tab within Citrix clients
bind = ALT, TAB, pass, class:^(Wfica)$

bindd = SUPER CTRL, Q, Lock Screen, exec, omarchy-lock-screen

## WINDOW RULES

# NOTE(robin): to disable transparancy for all windows
windowrule = match:class .*, opacity 1 override
# Launch Chromium into Workspace 2
windowrule = match:class chromium, workspace 2

# vim: ft=hyprlang
