## MONITORS

# Use single default monitor (see all monitors with: hyprctl monitors)
env = GDK_SCALE,1.75
# Monitor at work
monitor=DP-9,preferred,auto,1

## INPUTS

# use natural scrolling
input {
  kb_options = caps:escape

  touchpad {
    # Use natural (inverse) scrolling
    natural_scroll = true
  }
}

# Turn on natural scrolling for my Logitech mouse
device {
  name = lift-mouse
  natural_scroll = true
}

decoration {
    # Use round window corners
    rounding = 8
}

## BINDINGS

unbind = SUPER SHIFT, T
bindd = SUPER SHIFT, T, Todoist, exec, omarchy-launch-webapp "https://app.todoist.com/app/today"

# NOTE(robin): allow alt-tab within Citrix clients
bind = ALT, TAB, pass, class:^(Wfica)$

bindd = SUPER CTRL, Q, Lock Screen, exec, omarchy-lock-screen

## WINDOW RULES

# NOTE: do not use gaps when single application is active
# workspace = w[tv1], gapsout:0, gapsin:0
# workspace = f[1], gapsout:0, gapsin:0
# windowrulev2 = bordersize 0, floating:0, onworkspace:w[tv1]
# windowrulev2 = rounding 0, floating:0, onworkspace:w[tv1]
# windowrulev2 = bordersize 0, floating:0, onworkspace:f[1]
# windowrulev2 = rounding 0, floating:0, onworkspace:f[1]

# NOTE(robin): to disable transparancy for all windows
windowrule = opacity 1 1, class:.*

# Launch Chromium into Workspace 2
windowrule = workspace 2, class:chromium

# vim: ft=hyprlang
